//CSS
import './globals.css';
// COMPONENTS
import AppWrapper from './appWrapper';
interface RootLayoutProps {
  children: React.ReactNode;
}
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <AppWrapper>{props.children}</AppWrapper>
      </body>
    </html>
  );
}
