//CSS
import './globals.css';
// COMPONENTS
import AppWrapper from './appWrapper';
interface RootLayoutProps {
  children: React.ReactNode;
}
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/favicon/android-icon-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        url: '/favicon/favicon-32x32.png',
        sizes: '32x32',
        type: 'image/png',
      },
      {
        url: '/favicon/favicon-96x96.png',
        sizes: '96x96',
        type: 'image/png',
      },
      {
        url: '/favicon/favicon-16x16.png',
        sizes: '16x16',
        type: 'image/png',
      },
    ],
    other: [
      {
        rel: 'apple-touch-icon-precomposed',
        url: '/favicon/apple-icon-precomposed.png',
      },
    ],
  },
  manifest: '/favicon/manifest.json',
  themeColor: 'white',
  category: 'technology',
  verification: {
    google: 'google'
  },
};

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <AppWrapper>{props.children}</AppWrapper>
      </body>
    </html>
  );
}
